-- CREATE TABLE APP_EXCEL_TASKS TO TRACK BACKGROUND BATCH PROCESSING JOBS (IMPORT/EXPORT)
CREATE TABLE "APP_EXCEL_TASKS" (
    "ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE,
    "PROGRESS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
    "TOTAL_ROWS" NUMBER(10,0) DEFAULT 0,
    "SUCCESS_ROWS" NUMBER(10,0) DEFAULT 0,
    "FAILED_ROWS" NUMBER(10,0) DEFAULT 0,
    "ERROR_SUMMARY" CLOB,
    "RESULT_URL" VARCHAR2(500 CHAR),
    "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "PK_APP_EXCEL_TASKS" PRIMARY KEY ("ID") USING INDEX ENABLE,
    CONSTRAINT "CK_EXCEL_TASK_TYPE" CHECK (TYPE IN ('IMPORT', 'EXPORT')) ENABLE,
    CONSTRAINT "CK_EXCEL_TASK_STATUS" CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED')) ENABLE
);
