# ==================================================
# ORACLE DATABASE
# ==================================================

db.driver-class-name=oracle.jdbc.OracleDriver
db.url=jdbc:oracle:thin:@//localhost:1521/FREE
db.username=system
db.password=123456


# ==================================================
# HIKARICP CONNECTION POOL
# ==================================================

db.pool.pool-name=SpringMvcOraclePool
db.pool.minimum-idle=2
db.pool.maximum-pool-size=10
db.pool.connection-timeout=30000
db.pool.idle-timeout=600000
db.pool.max-lifetime=1800000


# ==================================================
# MYBATIS
# ==================================================

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.examp.springmvc.model
mybatis.map-underscore-to-camel-case=true
mybatis.cache-enabled=false


# ==================================================
# SPRING MVC VIEW
# ==================================================

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp