package com.examp.springmvc.shared.infrastructure.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.examp.springmvc.catalog.infrastructure.mapper.CategoryMapper;
import com.examp.springmvc.catalog.infrastructure.mapper.ProductMapper;
import com.examp.springmvc.catalog.infrastructure.persistence.CategoryDbEntity;
import com.examp.springmvc.catalog.infrastructure.persistence.ProductDbEntity;
import com.examp.springmvc.order.infrastructure.mapper.OrderItemMapper;
import com.examp.springmvc.order.infrastructure.mapper.OrderMapper;
import com.examp.springmvc.order.infrastructure.persistence.OrderDbEntity;
import com.examp.springmvc.order.infrastructure.persistence.OrderItemDbEntity;
import com.examp.springmvc.shared.domain.task.ExcelTask;
import com.examp.springmvc.shared.infrastructure.task.ExcelTaskMapper;
import com.examp.springmvc.user.infrastructure.mapper.UserCommandMapper;
import com.examp.springmvc.user.infrastructure.mapper.UserQueryMapper;
import com.examp.springmvc.user.infrastructure.persistence.UserDbEntity;
import java.math.BigDecimal;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = MyBatisIntegrationTestConfig.class)
@Transactional
public class MapperIntegrationTest {

    @Autowired
    private UserCommandMapper userCommandMapper;

    @Autowired
    private UserQueryMapper userQueryMapper;

    @Autowired
    private CategoryMapper categoryMapper;

    @Autowired
    private ProductMapper productMapper;

    @Autowired
    private OrderMapper orderMapper;

    @Autowired
    private OrderItemMapper orderItemMapper;

    @Autowired
    private ExcelTaskMapper excelTaskMapper;

    @Test
    public void testUserMappers() {
        // 1. Insert
        UserDbEntity user = new UserDbEntity();
        user.setUsername("integration_test_user");
        user.setFullName("Integration Test");
        user.setEmail("integration@example.com");
        user.setPhone("0987654321");
        user.setStatus("ACTIVE");
        user.setPassword("secure_password_hash");
        user.setRole("CUSTOMER");

        userCommandMapper.insert(user);
        assertNotNull(user.getId(), "User ID should be generated by sequence");

        // 2. Find by Username
        UserDbEntity foundByUsername = userQueryMapper.findByUsername("integration_test_user");
        assertNotNull(foundByUsername);
        assertEquals("Integration Test", foundByUsername.getFullName());

        // 3. Find by ID
        UserDbEntity foundById = userQueryMapper.findById(user.getId());
        assertNotNull(foundById);
        assertEquals("integration@example.com", foundById.getEmail());

        // 4. Update
        foundById.setFullName("Updated Full Name");
        userCommandMapper.update(foundById);

        UserDbEntity updated = userQueryMapper.findById(user.getId());
        assertEquals("Updated Full Name", updated.getFullName());

        // 5. Find All
        List<UserDbEntity> allUsers = userQueryMapper.findAll();
        assertFalse(allUsers.isEmpty());

        // 6. Delete
        userCommandMapper.deleteById(user.getId());
        assertNull(userQueryMapper.findById(user.getId()));
    }

    @Test
    public void testProductAndCategoryMappers() {
        // 1. Insert Category
        CategoryDbEntity category = new CategoryDbEntity();
        category.setName("Electronics");
        category.setCode("ELEC");
        category.setDescription("Electronic devices and gadgets");

        categoryMapper.insert(category);
        assertNotNull(category.getId());

        // 2. Insert Product linked to Category
        ProductDbEntity product = new ProductDbEntity();
        product.setCategoryId(category.getId());
        product.setSku("LAPTOP-001");
        product.setName("High Performance Laptop");
        product.setDescription("Core i9 Laptop");
        product.setPrice(new BigDecimal("1500.00"));
        product.setStatus(com.examp.springmvc.catalog.domain.model.ProductStatus.ACTIVE);
        product.setImageUrl("http://example.com/laptop.jpg");
        product.setStock(10);

        productMapper.insert(product);
        assertNotNull(product.getId());

        // 3. Find Product by ID
        ProductDbEntity foundProduct = productMapper.findById(product.getId());
        assertNotNull(foundProduct);
        assertEquals("Electronics", foundProduct.getCategoryName());
        assertEquals("LAPTOP-001", foundProduct.getSku());

        // 4. Find Product by SKU
        ProductDbEntity foundBySku = productMapper.findBySku("LAPTOP-001");
        assertNotNull(foundBySku);
        assertEquals(product.getId(), foundBySku.getId());

        // 5. Find Products by Category ID
        List<ProductDbEntity> productsByCategory = productMapper.findByCategoryId(category.getId());
        assertEquals(1, productsByCategory.size());

        // 6. Find Products by IDs
        List<ProductDbEntity> productsByIds = productMapper.findByIds(Collections.singletonList(product.getId()));
        assertEquals(1, productsByIds.size());

        // 7. Update Product
        foundProduct.setStock(5);
        productMapper.update(foundProduct);
        ProductDbEntity updatedProduct = productMapper.findById(product.getId());
        assertEquals(5, updatedProduct.getStock());

        // 8. Delete Product & Category
        productMapper.deleteById(product.getId());
        categoryMapper.deleteById(category.getId());

        assertNull(productMapper.findById(product.getId()));
        assertNull(categoryMapper.findById(category.getId()));
    }

    @Test
    public void testOrderMappers() {
        // 1. Insert Order
        OrderDbEntity order = new OrderDbEntity();
        order.setUserId(999L);
        order.setStatus("PENDING");
        order.setTotalAmount(new BigDecimal("250.50"));
        order.setReceiverName("John Doe");
        order.setReceiverPhone("0123456789");
        order.setShippingAddress("123 Main St, Hanoi");
        order.setNote("Fragile package");
        order.setPaymentMethod("COD");
        order.setPaymentStatus("UNPAID");

        orderMapper.insert(order);
        assertNotNull(order.getId());

        // 2. Insert Order Item linked to Order
        OrderItemDbEntity item = new OrderItemDbEntity();
        item.setOrderId(order.getId());
        item.setProductId(101L);
        item.setProductName("Mechanical Keyboard");
        item.setProductSku("KEY-001");
        item.setUnitPrice(new BigDecimal("125.25"));
        item.setQuantity(2);
        item.setSubtotal(new BigDecimal("250.50"));

        orderItemMapper.insert(item);
        assertNotNull(item.getId());

        // 3. Find Order by ID (checks join collection)
        OrderDbEntity foundOrder = orderMapper.findById(order.getId());
        assertNotNull(foundOrder);
        assertEquals("John Doe", foundOrder.getReceiverName());
        assertEquals(1, foundOrder.getItems().size());
        assertEquals("Mechanical Keyboard", foundOrder.getItems().get(0).getProductName());

        // 4. Find Order by User ID
        List<OrderDbEntity> userOrders = orderMapper.findByUserId(999L);
        assertEquals(1, userOrders.size());

        // 5. Find Order Items by Order ID
        List<OrderItemDbEntity> items = orderItemMapper.findByOrderId(order.getId());
        assertEquals(1, items.size());

        // 6. Update Order Status
        foundOrder.setStatus("COMPLETED");
        foundOrder.setPaymentStatus("PAID");
        orderMapper.update(foundOrder);

        OrderDbEntity updatedOrder = orderMapper.findById(order.getId());
        assertEquals("COMPLETED", updatedOrder.getStatus());
        assertEquals("PAID", updatedOrder.getPaymentStatus());

        // 7. Delete Order & Items
        orderItemMapper.deleteByOrderId(order.getId());
        orderMapper.deleteById(order.getId());

        assertNull(orderMapper.findById(order.getId()));
        assertTrue(orderItemMapper.findByOrderId(order.getId()).isEmpty());
    }

    @Test
    public void testExcelTaskMapper() {
        String taskId = java.util.UUID.randomUUID().toString();
        ExcelTask task = new ExcelTask(
                taskId,
                com.examp.springmvc.shared.domain.task.ExcelTaskType.IMPORT,
                com.examp.springmvc.shared.domain.task.ExcelTaskStatus.PROCESSING,
                100,
                0,
                0,
                0,
                "Testing errors",
                null,
                java.time.LocalDateTime.now(),
                java.time.LocalDateTime.now());

        excelTaskMapper.insert(task);

        ExcelTask found = excelTaskMapper.findById(taskId);
        assertNotNull(found);
        assertEquals(com.examp.springmvc.shared.domain.task.ExcelTaskType.IMPORT, found.getType());
        assertEquals(com.examp.springmvc.shared.domain.task.ExcelTaskStatus.PROCESSING, found.getStatus());
        assertEquals(100, found.getProgress());
        assertEquals("Testing errors", found.getErrorSummary());

        found.setProgress(50);
        found.setStatus(com.examp.springmvc.shared.domain.task.ExcelTaskStatus.COMPLETED);
        found.setSuccessRows(45);
        found.setFailedRows(55);
        found.setResultUrl("/test/download/url");
        excelTaskMapper.update(found);

        ExcelTask updated = excelTaskMapper.findById(taskId);
        assertNotNull(updated);
        assertEquals(50, updated.getProgress());
        assertEquals(com.examp.springmvc.shared.domain.task.ExcelTaskStatus.COMPLETED, updated.getStatus());
        assertEquals(45, updated.getSuccessRows());
        assertEquals(55, updated.getFailedRows());
        assertEquals("/test/download/url", updated.getResultUrl());

        List<ExcelTask> recent = excelTaskMapper.findRecentTasks(5);
        assertFalse(recent.isEmpty());
        assertTrue(recent.stream().anyMatch(t -> t.getId().equals(taskId)));
    }
}
